language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-dist -n

script:
  - ./vendor/bin/phpunit tests/
  - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=*/_files/* src/ tests/
